# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40

# [[main]]
#    name = "Create a Blog"
#    url = "post/create-a-blog/"
#    weight = 40

[[main]]
   name = "HTML"
   url = "html/html-fundamentals/"
   weight = 10

[[main]]
   name = "CSS"
   url = "css/css-fundamentals/"
   weight = 20

[[main]]
   name = "Static Websites"
   url = "#"
   identifier = "static-websites"
   weight = 40

   [[main]]
   name = "Introduction"
   url = "static-websites/static-websites-introduction/"
   parent = "static-websites"
   weight = 10

   [[main]]
   name = "HUGO (SSG)"
   url = "static-websites/hugo/"
   parent = "static-websites"
   weight = 20

# [[main]]
# name = "Wordpress (CMS)"
# url = "#"
# identifier = "wordpress"
# weight = 60

[[main]]
   name = "SEO"
   url = "seo/"
   identifier = "seo"
   weight = 90
   
   [[main]]
   name = "Keyword Research"
   url = "seo/keyword-research/"
   parent = "seo"
   weight = 30

   [[main]]
   name = "Technical SEO"
   url = "seo/technical-seo/"
   parent = "seo"
   weight = 60

[[main]]
  name = "Blog Posts"
  url = "#posts"
  weight = 340

[[main]]
  name = "About Us"
  url = "#about"
  weight = 350

[[main]]
  name = "Contact Us"
  url = "#contact"
  weight = 360

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
